import Head from "next/head";
import Image from "next/image";
import AboutMe from "./Components/AboutMe";
import Contact from "./Components/Contact";
import Education from "./Components/Education";
import Gallery from "./Components/Gallery";
import Hero from "./Components/Hero";
import NavBar from "./Components/NavBar";
import Section from "./Components/Section";

import Work from "./Components/Work";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Taye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Section>
        {" "}
        <Hero />{" "}
      </Section>
      <main className="flex flex-col ">
        <Section>
          {" "}
          <AboutMe />
        </Section>
        <Section color="#005257">
          <Education />
        </Section>

        <Section color="#005257">
          {" "}
          <Work />
        </Section>
        <Section color="#005257">
          <Gallery />
        </Section>
        <Section color="#005257">
          {" "}
          <Contact />
        </Section>
        {/* <Slidder /> */}
      </main>

      <footer className=""></footer>
    </div>
  );
}
